import home from './home'
import service from './services'
import pricipal from './Principal'
import Teachers from './Teachers'
import Students from './Students'
import studentGallery from './studentGallery'
import ImgSlider from './ImgSlider'
import teacherGallery from './teacherGallery'
import about from './about'
import blog from './blog'
import author from './author'
import blockContent from './blockContent'
import reviews from './reviews'

export const schemaTypes = [home, about, ImgSlider, service, pricipal, Teachers, Students, studentGallery, teacherGallery, blog,author,blockContent, reviews]
